from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, validator

class SectionSchema(BaseModel):
    """Schema for a single chapter section generated by the LLM."""
    title: str = Field(..., description="The title of the section.")
    content: str = Field(..., description="The full instructional content of the section.")
    images: List[Dict[str, Any]] = Field(default_factory=list, description="Optional images/diagrams for the section.")

    @validator("content")
    def validate_content_length(cls, v):
        word_count = len(v.split())
        if word_count < 150:
            raise ValueError(f"Content is too short ({word_count} words). Minimum is 150.")
        if word_count > 1000:  # Relaxed slightly from 900 for safety
            # We don't necessarily want to hard-fail on too long, but we can log it.
            pass
        return v

class ChapterSchema(BaseModel):
    """Schema for a full chapter (collection of sections) generated by the LLM."""
    sections: List[SectionSchema]

    @validator("sections")
    def validate_section_count(cls, v):
        if not (3 <= len(v) <= 4):
            raise ValueError(f"Expected 3-4 sections, but got {len(v)}.")
        return v
