class TeacherConstants:
    DEFAULT_MODEL_NAME = "gpt-4.1-mini"
    DEFAULT_MODEL_TEMPERATURE = 0.5
    DEFAULT_MAX_ITERATION = 8
    MODEL_NAME = "gpt-4.1-mini"
    MODEL_TEMPERATURE = 0.3
    MAX_ITERATION = 8
